```{r include=FALSE}
library(bipartite)
library(knitr)
library(knitcitations)
bibnet <- read.bibtex("~/Documents/BibTex/willow gall-ptoid networks.bib")
```

Plant genetic variation shapes the structure and function of herbivore-parasitoid networks (a work in progress)
-----------------------------------------------------------

Matthew A. Barbour, Jordi Bascompte, and Greg W. Crutsinger

### Objective

This paper examines how plant genetic variation influences herbivore-parasitoid interaction networks and how these networks shape selection pressures acting on herbivores.

Introduction
------------

If plant genotype has a significant effect on gall-parasitoid network structure

We tested the relative importance of plant genotype versus the environment in shaping gall-parasitoid networks.


### Research Questions

**(1)** How does plant genotype influence gall-parasitoid interaction networks?

**(2)** How do different interaction networks influence the form of natural selection acting on herbivore traits?

*Possible (3)* How does the simulated loss of plant genotypes influence gall-parasitoid interaction networks?

### Methods

**Quantifying gall-parasitoid interaction networks**

Following the method proposed by `r citet(bibnet["Poisot2012a"])`, we quantified the dissimilarity in quantitative gall-parasitoid networks across all willow tree sampled (n = 140).  

To measure the interaction strengths between each herbivore and parasitoid species in each network, we calculated the number of observed interactions divided by the sum of observed interactions between that herbivore and all parasitoid species.  This represents a quantitative measure of the relative impact of a particular parasitoid species on a herbivore species. *need to think about whether this is the actual measure I want*

**Other Approaches at Community Detection**
Following Albert et al. (in review at Ecology Letters) and `r citet(bibnet["Karrer2008"])`, we could compare the module composition of multiple networks.  Note that this approach will only work, if the same nodes are present in each network.  So if I find differences in "interaction turnover" between networks using `r citet(bibnet["Poisot2012a"])` method, I could follow up by examining how this interaction turnover influences the modular composition of the network.

Also, consider using hierarchical random graphs in the igraph library (in R) to detect hierarchical structure in the networks.  This method appears to utilize clustering at multiple levels, which may be useful for my tripartite networks of genotype-herbivore-parasitoid.  I also may be able to add ecological correlates (e.g. plant traits, gall size) that will influence community structure.  See `r citet(bibnet[c("Newman2011","Clauset2008"])` for examples.

Also, consider an individual-based approach (sensu `r citet(bibnet["Gomez2011"])`) at the plant and herbivore level.

Also, remember Jordi's advice which presents a pretty clear study.  Search for variation in modular composition of the network across genotypes.  Then use partial mantel tests and path analysis to see how genetic distance and plant traits influence the modular composition of these networks.  Then, I can identify genotype-modules (using bipartite modularity measures focused on genotypes, `r citet(bibnet[c("Guimara2007","Fortuna2009"])).  And follow up by seeing how variation in module composition influences natural selection acting on herbivores (section below).  But before this, I should explore the more fine scale structure (as suggested by Miguel) by looking at dissimilarity in interaction networks between individual trees and making sure all nodes are present on each tree.

**Quantifying natural selection**
Depending on the appropriate the scale (each tree, each genotype, or multiple genotypes) identified from the community detection analysis, I will quantify how differences in community structure influence the form and strength of natural selection acting on galling insects.  I need to find the R package, but I should be able to use a cubic spline method, as advocated by Dolph Schluter and `r citet(bibnet["Brodie1995"])`.

Older ideas
-----------
#### Q1
Build a meta-web of herbivore-parasitoid interactions by pooling across all genotypes (try a both qualitative and quantitative version, hopefully both will yield the same results)

Run an appropriate modularity algorithm to identify modules on the meta-web.

***Figure out how to quantify the frequency of representation of the different modules.***

Run a chi-square test based on the frequencies of each module occurring on each genotype to see whether there is an association.

### Q2
Build a meta-web of herbivore-parasitoid interactions by pooling across all genotypes (try both qualitative and quantitative version, hopefully both will yield the same results)

Evaluate the structure of the meta-web (nested or modular or both).

Compute the appropriate network measure for each replicate of each genotype and see whether I can detect any correlations between network structure and genetic distance or traits.

Could also use the method proposed in Poisot 2012 (Dissimilarity of Interaction Networks), but it doesn't examine how network structure changes (this may or may not be important, depending on whether I see any noticeable changes in my graphs of the different networks)

Could also see how the functional role of species (Guimera and Amaral Functional Cartography paper in Nature) change across genotypes.  Test this using a chi-square analysis based on genotypes and the seven different functional roles (I'm thinking now I won't see a big difference...)

***What I think may be a promising method***: Look for dissimilarity in module participation, by creating a matrix of all possible interactions (e.g H1,P1 H1,P2 H2,P1 etc.) for a particular module on a tree (or genotype), then calculate a bray-curtis dissimilarity within modules across the trees/genotypes.  Then see if this is associated with any particular gall and/or plant traits.**this is a more likely area where we will see gall trait variation influencing the network**

***Conversation with Rudolf***: Look for mantel correlation between dissimilarity in herbivore traits (e.g. gall size, multilocularity, etc.) and dissimilarity in network topology (e.g. see Bersier et al. 2002, for quantitative versions of network measures).  And see whether this correlation varies across genotypes.  Or simply look to see whether the quantitative versions of these network metrics vary across genotypes (similar to Tylianakis et al. 2007, but with different genotypes instead of habitats)

### Q3
Option 1: Use partial mantel tests and path analysis to see how genetic distance and trait dissimilarity influence dissimilarity in module frequency (either all modules combined, or modules individually).  Consider at first using all plant traits and then looking at individual traits.

Also, look for patterns between genotypes and herbivore traits, as well as herbivore traits and network topology.  Could use a mantel test for genetic distance and herbivore trait dissimilarity and measures of network topology.







